FROM ubuntu:18.10

RUN set -x \
    && apt-get update \
    && apt-get install -y \
                python3.7 \
                python3.7-dev \
                python3-pip \
                golang \
                libtesseract4 \
                tesseract-ocr \
                tesseract-ocr-rus \
                libsm6

