-- MySQL Script generated by MySQL Workbench
-- Sat Jun  8 17:12:48 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Contacts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Contacts` (
  `idContacts` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `phone_number` VARCHAR(20) NULL,
  `email` VARCHAR(255) NULL,
  PRIMARY KEY (`idContacts`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Attestat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Attestat` (
  `attestat_number` VARCHAR(14) NOT NULL,
  `average_grade` FLOAT NOT NULL,
  `attestat_img` MEDIUMBLOB NULL,
  PRIMARY KEY (`attestat_number`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`University`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`University` (
  `idUniversity` INT NOT NULL AUTO_INCREMENT,
  `university_name` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `full_address` VARCHAR(200) NULL,
  `gps_coord1` FLOAT NULL,
  `gps_coord2` FLOAT NULL,
  `website` VARCHAR(200) NULL,
  `Universitycol` VARCHAR(45) NULL,
  PRIMARY KEY (`idUniversity`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Faculty`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Faculty` (
  `idFaculty` INT NOT NULL AUTO_INCREMENT,
  `faculty_name` VARCHAR(80) NOT NULL,
  `descript` TEXT NOT NULL,
  `dean` VARCHAR(80) NOT NULL,
  `num_of_foreign_students` SMALLINT NULL DEFAULT 0,
  `website` VARCHAR(200) NULL,
  `address` VARCHAR(200) NOT NULL,
  `Con_idContacts` INT UNSIGNED NULL,
  `idUniversity` INT NULL,
  PRIMARY KEY (`idFaculty`),
  INDEX `fk_Faculty_Contacts1_idx` (`Con_idContacts` ASC),
  INDEX `fk_University_idx` (`idUniversity` ASC),
  CONSTRAINT `fk_Faculty_Contacts1`
    FOREIGN KEY (`Con_idContacts`)
    REFERENCES `mydb`.`Contacts` (`idContacts`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_University`
    FOREIGN KEY (`idUniversity`)
    REFERENCES `mydb`.`University` (`idUniversity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Department` (
  `department_name` VARCHAR(100) NOT NULL,
  `director` VARCHAR(80) NOT NULL,
  `number_of_educators` SMALLINT UNSIGNED NULL,
  `number_of_researchers` SMALLINT UNSIGNED NULL,
  `website` VARCHAR(100) NULL,
  `address` VARCHAR(70) NOT NULL,
  `Con_idContacts` INT UNSIGNED NULL,
  `Fac_faculty_id` INT NOT NULL,
  `Departmentcol` VARCHAR(45) NULL,
  PRIMARY KEY (`department_name`),
  INDEX `fk_Department_Contacts1_idx` (`Con_idContacts` ASC),
  INDEX `fk_Faculty_id_idx` (`Fac_faculty_id` ASC),
  CONSTRAINT `fk_Department_Contacts1`
    FOREIGN KEY (`Con_idContacts`)
    REFERENCES `mydb`.`Contacts` (`idContacts`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Faculty_id`
    FOREIGN KEY (`Fac_faculty_id`)
    REFERENCES `mydb`.`Faculty` (`idFaculty`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Applicant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Applicant` (
  `main_document_number` VARCHAR(12) NOT NULL,
  `first_second_etc_names` VARCHAR(80) NOT NULL,
  `brith_date` DATE NOT NULL,
  `Con_idContacts` INT UNSIGNED NULL,
  `attestat_number` VARCHAR(14) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  `Photo` MEDIUMBLOB NULL,
  `ege_cert_number` VARCHAR(14) NULL,
  PRIMARY KEY (`main_document_number`),
  INDEX `fk_Applicant_Contacts1_idx` (`Con_idContacts` ASC),
  INDEX `fk_Applicant_Certificate1_idx` (`attestat_number` ASC),
  CONSTRAINT `fk_Applicant_Contacts1`
    FOREIGN KEY (`Con_idContacts`)
    REFERENCES `mydb`.`Contacts` (`idContacts`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Applicant_Certificate1`
    FOREIGN KEY (`attestat_number`)
    REFERENCES `mydb`.`Attestat` (`attestat_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Programme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Programme` (
  `idProgramme` INT NOT NULL,
  `programme_name` VARCHAR(80) NOT NULL,
  `field_name` VARCHAR(60) NOT NULL,
  `descript` TEXT NOT NULL,
  `education_level` VARCHAR(30) NOT NULL,
  `language_of_study` VARCHAR(20) NOT NULL,
  `fee_per_year` MEDIUMINT UNSIGNED NOT NULL,
  `form_of_education` VARCHAR(14) NOT NULL,
  `studies_duration` VARCHAR(10) NOT NULL,
  `no_pay_positions` SMALLINT NOT NULL,
  `pay_positions` SMALLINT NOT NULL,
  `any_partner_univers` TINYINT(1) NOT NULL,
  `programme_director` VARCHAR(80) NOT NULL,
  `person_to_contact` VARCHAR(80) NULL,
  `Con_idContacts` INT UNSIGNED NULL,
  `Dep_department_name` VARCHAR(100) NOT NULL,
  `idUniversity` INT NULL,
  `docs_url` VARCHAR(200) NOT NULL,
  `idFaculty` INT NULL,
  `docs_start_date` DATETIME NULL,
  `docs_end_date` DATETIME NULL,
  INDEX `fk_Programme_Contacts1_idx` (`Con_idContacts` ASC),
  INDEX `fk_Programme_University1_idx` (`idUniversity` ASC),
  PRIMARY KEY (`idProgramme`),
  INDEX `fk_Programme_Faculty_idx` (`idFaculty` ASC),
  CONSTRAINT `fk_Programme_Contacts1`
    FOREIGN KEY (`Con_idContacts`)
    REFERENCES `mydb`.`Contacts` (`idContacts`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Programme_University1`
    FOREIGN KEY (`idUniversity`)
    REFERENCES `mydb`.`University` (`idUniversity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Programme_Faculty`
    FOREIGN KEY (`idFaculty`)
    REFERENCES `mydb`.`Faculty` (`idFaculty`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ExamResult`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ExamResult` (
  `idExamResult` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `exam_name` VARCHAR(80) NOT NULL,
  `result_grade` TINYINT(3) UNSIGNED NOT NULL,
  `App_main_document_number` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`idExamResult`, `App_main_document_number`),
  INDEX `fk_ExamResult_Applicant1_idx` (`App_main_document_number` ASC),
  CONSTRAINT `fk_ExamResult_Applicant1`
    FOREIGN KEY (`App_main_document_number`)
    REFERENCES `mydb`.`Applicant` (`main_document_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`non_ege_exams_dictionary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`non_ege_exams_dictionary` (
  `idNonEgeExam` INT NOT NULL,
  `exam_name` VARCHAR(100) NULL,
  `max_value` INT NULL,
  PRIMARY KEY (`idNonEgeExam`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Programme_non_ege_ExamRequired`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Programme_non_ege_ExamRequired` (
  `idProgramme` INT NOT NULL,
  `idNonEgeExam` INT NOT NULL,
  `min_value` VARCHAR(45) NULL,
  `exam_date` DATETIME NULL,
  PRIMARY KEY (`idProgramme`, `idNonEgeExam`),
  INDEX `fk_non_ege_exam_idx` (`idNonEgeExam` ASC),
  CONSTRAINT `fk_Programme_has_ExamRequired_Programme1`
    FOREIGN KEY (`idProgramme`)
    REFERENCES `mydb`.`Programme` (`idProgramme`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_non_ege_exam`
    FOREIGN KEY (`idNonEgeExam`)
    REFERENCES `mydb`.`non_ege_exams_dictionary` (`idNonEgeExam`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Applicant_has_Programme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Applicant_has_Programme` (
  `Applicant_main_document_number` VARCHAR(12) NOT NULL,
  `Programme_programme_name` VARCHAR(80) NOT NULL,
  `idProgramme` INT NULL,
  PRIMARY KEY (`Applicant_main_document_number`, `Programme_programme_name`),
  INDEX `fk_Applicant_has_Programme_Applicant1_idx` (`Applicant_main_document_number` ASC),
  INDEX `fk_programme_id_idx` (`idProgramme` ASC),
  CONSTRAINT `fk_Applicant_has_Programme_Applicant1`
    FOREIGN KEY (`Applicant_main_document_number`)
    REFERENCES `mydb`.`Applicant` (`main_document_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_programme_id`
    FOREIGN KEY (`idProgramme`)
    REFERENCES `mydb`.`Programme` (`idProgramme`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ege_dictionary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ege_dictionary` (
  `egeid` INT NOT NULL,
  `ege_name` VARCHAR(45) NULL,
  PRIMARY KEY (`egeid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ege_requirements`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ege_requirements` (
  `egeid` INT NOT NULL,
  `min_value` INT NULL,
  `idUniversity` INT NULL,
  `idProgramme` INT NULL,
  PRIMARY KEY (`egeid`),
  INDEX `fk_Programme_ege_req_idx` (`idProgramme` ASC),
  CONSTRAINT `ege_id`
    FOREIGN KEY (`egeid`)
    REFERENCES `mydb`.`ege_dictionary` (`egeid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Programme_ege_req`
    FOREIGN KEY (`idProgramme`)
    REFERENCES `mydb`.`Programme` (`idProgramme`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ege_results`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ege_results` (
  `key` INT NOT NULL AUTO_INCREMENT,
  `ege_id` INT NOT NULL,
  `ege_value` INT NULL,
  `ege_cert_number` VARCHAR(14) NOT NULL,
  PRIMARY KEY (`key`, `ege_id`, `ege_cert_number`),
  INDEX `fk_ege_cert_number_idx` (`ege_cert_number` ASC),
  CONSTRAINT `fk_ege_id`
    FOREIGN KEY (`ege_id`)
    REFERENCES `mydb`.`ege_dictionary` (`egeid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ege_cert_number`
    FOREIGN KEY (`ege_cert_number`)
    REFERENCES `mydb`.`Applicant` (`main_document_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`documet_dictionary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`documet_dictionary` (
  `idDoc` INT NOT NULL,
  `doc_name` VARCHAR(200) NULL,
  `is_common_doc` INT NULL DEFAULT 0,
  PRIMARY KEY (`idDoc`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`docs_required`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`docs_required` (
  `key` INT NOT NULL,
  `idProgramme` INT NOT NULL,
  `idDoc` INT NOT NULL,
  PRIMARY KEY (`idProgramme`, `key`, `idDoc`),
  INDEX `fk_Doc_idx` (`idDoc` ASC),
  CONSTRAINT `fk_Programme`
    FOREIGN KEY (`idProgramme`)
    REFERENCES `mydb`.`Programme` (`idProgramme`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Doc`
    FOREIGN KEY (`idDoc`)
    REFERENCES `mydb`.`documet_dictionary` (`idDoc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`applicant_docs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`applicant_docs` (
  `idapplicant_docs` INT NOT NULL,
  PRIMARY KEY (`idapplicant_docs`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
